### ISSUE TITLE
INSTITUTE: Issues related to design swap

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#307]
Test site: https://saw.middlebury.edu/~imcbride/institute-redesign/academics
--- 
- [x] ~[Add a `theme-institute` body class with the appropriate color](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-806850873)~
- [x] ~[Add the Institute shield for the header](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-806820212)~
- [ ] [New footer does not support separate styles for multiple lines of text](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-627484156).
- [ ] [New footer CTA blocks only allow one line of text](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-627485710)
- [ ] ~[New header CTA blocks only allow one line of text](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-627523710)~
- [ ] [Determine how to handle link list grids that have images](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-627549220)
- [x] ~[Determine how to handle CTA nav menu on the Top Level template](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-628871972)~
- [x] ~[Handle "hidden" Fellows menu in Admissions](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-628873054)~
- [x] ~[Content issue: the featured image used on some top level pages isn't tall enough](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-630225087)~
- [ ] [Port styles for Emergency Contacts block](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-632109588)
- [x] ~[Differences in Campus / Program Spotlight component](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-632231496)~
- [x] ~DRUPAL ISSUE: [Homepage is using the middlebury_theme rather than the middlebury_institute_theme](https://github.com/middlebury/drupal8/issues/1453#issuecomment-806844034)~
- [x] ~DRUPAL ISSUE: [Update homepage template](https://github.com/middlebury/drupal8/issues/1453)~
- [x] ~DRUPAL ISSUE: [Update newsroom template](https://github.com/middlebury/drupal8/issues/1453)~
- [ ] DRUPAL ISSUE: [Update events template](https://github.com/middlebury/drupal8/issues/1453)
- [ ] ~[Replace the MiddAlert bar notice with a nav link](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-814866807)~
- [ ] [Add new form component to program pages with modal form on sub-pages](https://github.com/middlebury/midd-frontend/issues/307#issuecomment-814868445)

The Drupal issues will become issues for review here after we've completed the backend updates to support them.

**Comment by imcbride** [comment]
The new footer (left) has two lines of text for "site slogan" and "site name" with the same style, causing a regression from the Institute's design (right) which provides separate styles for each line of text in the footer.

![image](https://user-images.githubusercontent.com/662895/81725780-5d32de80-9454-11ea-8a7c-d7379a8ed43d.png)

**Comment by imcbride** [comment]
The CTA Footer block type (left) only supports one line of text, but the Institute's footer CTAs (right) have two lines of text.

![image](https://user-images.githubusercontent.com/662895/81726085-ca467400-9454-11ea-96e6-9b2c07bf0ae3.png)

**Comment by imcbride** [comment]
Perhaps not an issue, but the current MIIS header CTA (left) allows two lines of text while the CTA banner (right) only allows one.

![image](https://user-images.githubusercontent.com/662895/81732845-11d1fd80-945f-11ea-9d42-ceecac38f0c3.png)

**Comment by imcbride** [comment]
The institute site has a number of link list grids with featured images. These work relatively well using the existing markup for the Quick Links component with the image printed above the link, but we may want to come up with a different solution.

![image](https://user-images.githubusercontent.com/662895/81737479-282f8780-9466-11ea-8d46-e77516d544f4.png)

**Comment by imcbride** [comment]
Assuming we want to use the Top Level design for Program and Center pages, the extra CTA menu currently shown below the navigation menu on the right ("Find out if IEM is right for you" and "Scholarships" in the screenshot) will need a solution.

![image](https://user-images.githubusercontent.com/662895/81982962-98721080-9600-11ea-8540-7781b3d17bf1.png)

**Comment by imcbride** [comment]
Not a design issue per se, and probably a question for the content team, but the Admissions site has two top level menu links in order to have a "hidden" menu for Fellows.

![image](https://user-images.githubusercontent.com/662895/81983175-ec7cf500-9600-11ea-90b2-705fc634d6db.png)

**Comment by imcbride** [comment]
This is a general issue that affects all school sites. When the top level page title is very long it pushes the navigation bar below the featured image instead of overlapping it.

![image](https://user-images.githubusercontent.com/662895/82225606-6b20ad80-98f3-11ea-8b3a-3b7c3b573171.png)

**Comment by imcbride** [comment]
There are custom styles for the Emergency Contacts block on the Students Audience page that will need to be ported over to this project.

![image](https://user-images.githubusercontent.com/662895/82567659-a9b0a500-9b4b-11ea-9b32-6c2bd9bb25d8.png)

**Comment by imcbride** [comment]
There are significant differences between the Program / Campus Spotlight components on the Institute site and the Class Profiles component (Stat Panel) on the School sites. This can be kind of faked, but definitely warrants a review of the component.

![image](https://user-images.githubusercontent.com/662895/82585853-b1c90e80-9b64-11ea-94b3-10b2e27fa291.png)
![image](https://user-images.githubusercontent.com/662895/82585891-bee5fd80-9b64-11ea-9e58-e63a57812bda.png)

**Comment by imcbride** [comment]
Add the Institute shield to the header. We need a version of the shield and wordmark graphic for the institute on a white or transparent background.

Example:
https://saw.middlebury.edu/~imcbride/institute-redesign/academics
https://www.middlebury.edu/institute/academics

Institute:
![image](https://user-images.githubusercontent.com/662895/112486184-07a4af00-8d52-11eb-957d-b10af3ec9ef1.png)

School:
![image](https://user-images.githubusercontent.com/662895/112486003-e17f0f00-8d51-11eb-8483-135ae803fccc.png)

**Comment by imcbride** [comment]
[DRUPAL ISSUES] Homepage is using the middlebury_theme rather than the middlebury_institute_theme. This should be using the sub-theme so that it gets the appropriate header and footer.

School:
![image](https://user-images.githubusercontent.com/662895/112486524-54888580-8d52-11eb-972c-cd706ecb36eb.png)

**Comment by imcbride** [comment]
Add `theme-institute` body class with appropriate color.

This appears to be in place but I'll leave this open to allow confirmation that the correct color is being used.

Example:
https://saw.middlebury.edu/~imcbride/institute-redesign/academics

School:
![image](https://user-images.githubusercontent.com/662895/112489302-b3e79500-8d54-11eb-8ce7-9a1745807e61.png)

**Comment by aaronMidd** [comment]
Remove the MiddAlert bar and Add a new Nav Link for "Return to Campus" planning, or whatever the announcement is.

![Screen Shot 2021-04-07 at 8 16 18 AM](https://user-images.githubusercontent.com/74672095/113864997-94e7fa80-9779-11eb-8581-ef93522a1673.png)

**Comment by aaronMidd** [comment]
### New Form Component

- We plan to drive ad traffic to program landing pages (it has better quality scores)
- Form can go below Opening paragraph
- First, last, email, how did you hear about us? - form fields needed (plus solution for program of interest below)
- We would want to understand which program dynamically (either by the page or specified by hidden field set in the component
- For main pages having an embedded form on the page.
- On sub pages having a button - with modal form - similar to what is happening today. See screenshot below.

![Screen Shot 2021-04-07 at 8 19 04 AM](https://user-images.githubusercontent.com/74672095/113865339-f740fb00-9779-11eb-9402-795c26c17265.png)
